env:
  browser: true
  es2021: true
  node: true
extends:
  - google
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'prettier'
rules: {
  require-jsdoc: 0,
  prettier/prettier: 2
}
